name: CI

on:
  push:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read

env:
  UseMultiToolTask: true

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        config: [Release]
        platform: [Win32]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: microsoft/setup-msbuild@v1

      - uses: Trass3r/setup-cpp@master

      - name: Build
        run: msbuild /m \
          /p:Configuration=${{ matrix.config }} \
          /p:Platform=${{ matrix.platform }} \
          dxwrapper.sln

      - name: Upload DX8 Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dx8 game binaries
          path: bin/${{ matrix.config }}/dx8/*

      - name: Upload DX9 Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dx9 game binaries
          path: bin/${{ matrix.config }}/dx9/*
